# -*- coding: utf-8 -*-
"""novo_6andar_29abril2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lrftMBy58XzGDw1qdeB6NTKMn5Hoq9iy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import unicodedata
import re
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import warnings
warnings.filterwarnings("ignore")
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import KFold, cross_val_score

arquivo_principal = '/content/imoveis_sextoandar_NIVEL_2_COMPLETO (1).csv'

print("Iniciando auditoria da base de dados...")

# 1. Carrega a base completa
df = pd.read_csv(arquivo_principal)
total_linhas = len(df)

# 2. Conta quantas URLs duplicadas existem
# O método duplicated() marca como True qualquer URL que já tenha aparecido antes
qtd_duplicadas = df.duplicated(subset=['URL']).sum()

if qtd_duplicadas > 0:
    print(f"⚠️ Alerta: Encontramos {qtd_duplicadas} registros duplicados em um total de {total_linhas} linhas.")

    # 3. Remove as duplicatas.
    # keep='last' garante que, se houver repetidos, ele mantém o dado da raspagem mais recente
    df_limpo = df.drop_duplicates(subset=['URL'], keep='last')

    # 4. Salva o arquivo limpo por cima do antigo
    df_limpo.to_csv(arquivo_principal, index=False, encoding='utf-8-sig')

    print(f"✅ Limpeza concluída! Base salva com {len(df_limpo)} imóveis únicos.")
else:
    print(f"🏆 Parabéns! Sua base está 100% limpa. Todos os {total_linhas} imóveis são únicos.")

# ==========================================
# 1. VER DADOS
# ==========================================
print("--- PRIMEIRAS 5 LINHAS ---")
# O .head() mostra as 5 primeiras linhas para você ver como a tabela está formatada
print(df.head())
print("\n" + "="*50 + "\n")

# ==========================================
# 2. NOMES DAS COLUNAS E QUANTIDADES
# ==========================================
print("--- INFORMAÇÕES GERAIS DAS COLUNAS ---")
# O .info() mostra o total de linhas, os nomes de todas as colunas,
# o tipo de cada dado (texto, número) e quantos dados NÃO são nulos.
df.info()
print("\n" + "="*50 + "\n")

# ==========================================
# 3. CONTAGEM DE VALORES VAZIOS (NULOS)
# ==========================================
print("--- QUANTIDADE DE VALORES VAZIOS POR COLUNA ---")
# Mostra exatamente onde estão os "buracos" na sua base de dados
print(df.isnull().sum())
print("\n" + "="*50 + "\n")

# ==========================================
# 4. TAMANHO TOTAL DO DATASET
# ==========================================
print("--- TAMANHO DO DATASET ---")
linhas, colunas = df.shape
print(f"Sua base possui {linhas} imóveis (linhas) e {colunas} características (colunas).")
print("\n" + "="*50 + "\n")

# ==========================================
# 5. RESUMO ESTATÍSTICO BÁSICO
# ==========================================
print("--- RESUMO ESTATÍSTICO ---")
# O .describe() vai tentar mostrar médias, mínimos, máximos e quantidades.
# O 'include="all"' força ele a mostrar um resumo até das colunas de texto.
print(df.describe(include='all'))

# ========== CARREGAMENTO E LIMPEZA DOS DADOS ==========
print("📊 CARREGANDO E LIMPEZANDO DADOS...")

# Carregamento dos dados
df = pd.read_csv(arquivo_principal)

# Funções de limpeza
def clean_str(x):
    if pd.isna(x): return ''
    s = str(x).strip()
    s = unicodedata.normalize('NFKD', s).encode('ASCII', 'ignore').decode('utf-8')
    s = s.replace('\xa0',' ').replace('\u200b','').strip()
    return s

def clean_money(x):
    if pd.isna(x): return np.nan
    s = clean_str(x).replace('R$', '').replace('.', '').replace(',', '.').strip()
    try: return float(s)
    except: return np.nan

def clean_number(x):
    if pd.isna(x): return np.nan
    s = clean_str(x).lower()
    s = re.sub(r'm2|metros|quartos?|banheiros?|vaga[s]?|andar|andares?', '', s)
    s = re.sub(r'[^\d.,-]', '', s).replace(',', '.').strip()
    try: return float(s)
    except: return np.nan

def normalize_text(s):
    if pd.isna(s): return ''
    s = str(s).strip().lower()
    s = unicodedata.normalize('NFKD', s).encode('ASCII', 'ignore').decode('utf-8')
    return s

# Aplicando limpeza
for col in ['Aluguel', 'Condominio', 'IPTU', 'Total']:
    if col in df.columns:
        df[col] = df[col].apply(clean_money)

for col in ['Metragem', 'Quartos', 'Banheiros']:
    if col in df.columns:
        df[col] = df[col].apply(clean_number)

df['Bairro'] = df['Bairro'].apply(normalize_text)

# Remoção de registros incompletos
df.dropna(subset=['Total', 'Metragem', 'Quartos', 'Bairro', 'Banheiros'], inplace=True)

# Remoção de outliers
p99 = df['Total'].quantile(0.99)
df = df[df['Total'] <= p99]

print(f"✅ Dados limpos: {len(df)} registros")

# ========== PREPARAÇÃO DOS DADOS ==========
print("\n🔧 PREPARANDO DADOS PARA MODELAGEM...")

# Usando 4 variáveis solicitadas
X = df[['Metragem', 'Quartos', 'Banheiros', 'Bairro']]
y = df['Total']

# Divisão treino/teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Pré-processamento
num_cols = ['Metragem', 'Quartos', 'Banheiros']
cat_cols = ['Bairro']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', num_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols)
    ]
)

# ========== AVALIAÇÃO DE MODELOS ==========
print("\n🤖 COMPARANDO MODELOS DE MACHINE LEARNING...")

def avaliar_modelo(modelo, nome):
    # Cria o pipeline com o pré-processamento e o modelo
    pipe = Pipeline(steps=[('preprocessor', preprocessor), ('model', modelo)])


    # 1. VALIDAÇÃO CRUZADA (K-FOLD) NO CONJUNTO DE TREINO
    # ---------------------------------------------------------
    # Divide os dados de treino em 5 partes, embaralhando antes
    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    # Calcula o R² para cada um dos 5 "simulados" e tira a média
    cv_scores = cross_val_score(pipe, X_train, y_train, cv=kf, scoring='r2')
    r2_cv_medio = cv_scores.mean()


    # 2. TREINO FINAL E AVALIAÇÃO NO CONJUNTO DE TESTE

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    r2_test = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))

    print(f"📈 {nome}:")
    print(f"   R² (Média K-Fold): {r2_cv_medio:.4f} | R² (Teste Final): {r2_test:.4f}")
    print(f"   MAE: R$ {mae:,.2f} | RMSE: R$ {rmse:,.2f}\n")

    return {
        "Modelo": nome,
        "R2_CV": r2_cv_medio,
        "R2_Test": r2_test,
        "MAE": mae,
        "RMSE": rmse,
        "pipeline": pipe
    }

# Teste de modelos
resultados = []

resultados.append(avaliar_modelo(
    LinearRegression(),
    "Regressão Linear"
))

resultados.append(avaliar_modelo(
    RandomForestRegressor(n_estimators=200, random_state=42),
    "Random Forest"
))

resultados.append(avaliar_modelo(
    XGBRegressor(n_estimators=300, learning_rate=0.1, max_depth=6, random_state=42),
    "XGBoost"
))

resultados.append(avaliar_modelo(
    MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=500, random_state=42),
    "Rede Neural (MLP)"
))


melhor_resultado = max(resultados, key=lambda x: x['R2_Test'])
melhor_modelo = melhor_resultado['pipeline']

print(f"🏆 MELHOR MODELO: {melhor_resultado['Modelo']} (R² Teste: {melhor_resultado['R2_Test']:.4f})")